// Generated by CoffeeScript 1.8.0
(function() {
  var bl, http, opt, res;

  http = require('http');

  bl = require('bl');

  opt = process.argv[2];

  res = http.get(opt, function(res) {
    return res.pipe(bl(function(err, data) {
      if (err != null) {
        return console.log(err);
      } else {
        console.log(data.length);
        return console.log(data.toString());
      }
    }));
  });

}).call(this);

//# sourceMappingURL=httpcollect.js.map
