// Generated by CoffeeScript 1.8.0

/*
"/api/parsetime"
{
"hour": 14,
"minute": 23,
"second": 15
}

"/api/unixtime"
{ "unixtime": 1376136615474 }
 */

(function() {
  var http, port, server, url;

  http = require('http');

  url = require('url');

  port = process.argv[2];

  server = http.createServer(function(request, response) {
    var data, date;
    if (request.method === 'GET') {
      data = url.parse(request.url, true);
      if (data.pathname === "/api/parsetime") {
        date = new Date(data.query.iso);
        response.writeHead(200, {
          'Content-Type': 'application/json'
        });
        response.write(JSON.stringify({
          "hour": date.getHours(),
          "minute": date.getMinutes(),
          "second": date.getSeconds()
        }));
        return response.end();
      } else if (data.pathname === "/api/unixtime") {
        response.writeHead(200, {
          'Content-Type': 'application/json'
        });
        response.write(JSON.stringify({
          "unixtime": Math.round(new Date(data.query.iso).getTime())
        }));
        return response.end();
      }
    }
  }).listen(port);

}).call(this);

//# sourceMappingURL=jsonApiServer.js.map
