// Generated by CoffeeScript 1.8.0
(function() {
  var http, map, port, server;

  http = require('http');

  map = require('through2-map');

  port = process.argv[2];

  server = http.createServer(function(request, response) {
    if (request.method === 'POST') {
      return request.pipe(map(function(chunk) {
        return chunk.toString().toUpperCase();
      })).pipe(response);
    }
  }).listen(port);

}).call(this);

//# sourceMappingURL=httpcapital.js.map
