// Generated by CoffeeScript 1.8.0
(function() {
  var file, fs, http, port, server;

  http = require('http');

  fs = require('fs');

  port = process.argv[2];

  file = process.argv[3];

  server = http.createServer(function(request, response) {
    var f;
    f = fs.createReadStream(file);
    return f.pipe(response);
  }).listen(port);

}).call(this);

//# sourceMappingURL=httpserver.js.map
